export function getDecodedContent(str: string): string;
export function matchDocUrl(arr: any[]): boolean;
export function getFileExtension(media?: string, subst?: string): string;
export function getNodeNS(node: object): object;
export function getXmlnsPrefixedNamespace(elm: object, attr: string): string;
export function setAttributeNS(elm: object, node?: object): void;
export function createElement(node: object): object;
export function createFragment(nodes: any[]): object;
export function appendChildNodes(elm: object, node: object): object;
export function createXmlBasedDomString(node: object): string | null;
export function createRangeArr(range: object): any[];
export function createDomStringFromSelectionRange(sel: object): string | null;
export function serializeDomString(domstr: string, mime: string, reqElm?: boolean): string | null;
export function getText(nodes: object, pre?: boolean): string;
export function getAncestorId(node: object): string | null;
export function isEditable(node: object): boolean;
export function isContentTextNode(node: object): boolean;
export function isEditControl(elm: object): boolean;
export function getEditableElm(node: object): object;
export function filterEditableElements(localName: string, query: string, force?: boolean): any[];
export function createParagraphedContent(value: string, ns?: string): object;
